"""Generator of subagent definitions: `agent.yaml` + `prompt.md` → `.claude/agents/<slug>.md`.

A Claude Code agent definition is a single markdown file: YAML frontmatter with the name, the
description and the list of allowed tools, followed by the system prompt as the body. Everything
except the body is derived from the agent's contract, so this file is never written by hand;
only the source in `library/agents/<name>/` is edited.

The frontmatter shape comes not from the documentation but from the stage 0 probe: `tools` as a
comma-separated string and `mcpServers` as a block list. That is exactly how `probe-researcher`
was declared, and in a live run it came up under its `agentType` and reached
`mcp__tavily-remote__tavily_search` (`docs/decisions/2026-08-13-probe-findings.md`, items 2 and 3).

Document-type profiles (facet SPEC §6) arrive through the `skills:` frontmatter field: the runtime
loads `.claude/skills/<name>/SKILL.md` into the agent's context at launch. A profile that does not
exist is **silently skipped** by the runtime: the warning goes only to the debug log, the agent
starts without its contract, and the run does not show it. So the build checks every named
profile on disk and fails if one is missing. It is the same kind of silent failure as a port
pointing at a file nobody wrote.

Every agent carries `omitClaudeMd: true`. By default Claude Code puts the whole CLAUDE.md
hierarchy into the context of every subagent as a separate instructions block. Checked against a
carrier agent's transcript: 40 KB at the time of measurement, and the writer rereads it on every
turn. The agent does not need it: the prompt describes its role, the profile its document, and
the task from the script its inputs and outputs. CLAUDE.md remains the instructions for the
developer session (Claude Code ≥ 2.1.271).

The model is deliberately not written here. A library agent has none: `params.model` belongs to
the pipeline node, because the same agent costs different money in different pipelines. The model
is set by the `agent()` call in the script; that is the job of `emit_workflow.py`.
"""

from __future__ import annotations

from collections.abc import Iterable
from pathlib import Path

import yaml

from facet.models.agent import AgentSpec

# Mapping of contract capabilities to Claude Code tools. `vision` is not a separate tool:
# images are read by the same `Read`, so `read` and `vision` collapse into one entry and the
# duplicate is dropped.
CAPABILITY_TOOLS: dict[str, tuple[str, ...]] = {
    "read": ("Read",),
    "edit": ("Write", "Edit"),
    "bash": ("Bash",),
    "webfetch": ("WebFetch",),
    "vision": ("Read",),
}

# The tool order in the file is fixed, not inherited from `needs`: one YAML must produce one and
# the same file, otherwise a diff of the generated files stops meaning anything.
TOOL_ORDER = ("Read", "Write", "Edit", "Bash", "WebFetch")

MCP_PREFIX = "mcp:"

AGENT_YAML = "agent.yaml"
PROMPT_MD = "prompt.md"
SKILL_MD = "SKILL.md"

# English, because this line ends up INSIDE the agent's system prompt — the whole generated file
# is the prompt, comment included. Everything an agent reads is English; the target language
# appears only as material the agent must match literally, such as a critic's dictionary of
# clichés in the language it reviews.
#
# It names emit_agents rather than a `collimate build` command, because no such command exists.
GENERATED_MARKER = (
    "<!-- Generated by facet/emit_agents.py from library/agents/{name}/. "
    "Edit the source, not this file. -->"
)


def slug_of(name: str) -> str:
    """`article_critic` → `article-critic`.

    Library names are snake_case, while Claude Code names its agents with hyphens: so do the
    built-in ones, and so did our `probe-researcher`, which launched. The hyphen is chosen as
    the proven form; the file name and the `agentType` name come from one function, so they
    cannot diverge.
    """
    return name.replace("_", "-")


def mcp_servers_of(needs: Iterable[str]) -> list[str]:
    """MCP servers named by the contract: `"mcp:tavily-remote"` → `tavily-remote`."""
    return sorted({cap[len(MCP_PREFIX) :] for cap in needs if cap.startswith(MCP_PREFIX)})


def tools_of(needs: Iterable[str]) -> list[str]:
    """Contract capabilities → the tool list for the frontmatter.

    An MCP server enters the list as one entry `mcp__<server>` without a tool name: in the
    probe, an agent declared this way got access to both `tavily_search` and
    `tavily_extract`, so the prefix works as a permission for the whole server.
    """
    caps = list(needs)
    unknown = [c for c in caps if c not in CAPABILITY_TOOLS and not c.startswith(MCP_PREFIX)]
    if unknown:
        # A capability added to the model without a mapping here must break the build: an
        # empty tool list silently handed to an agent is far more expensive to debug.
        raise ValueError(f"capabilities with no tool mapping: {sorted(unknown)}")

    granted = {tool for cap in caps for tool in CAPABILITY_TOOLS.get(cap, ())}
    ordered = [tool for tool in TOOL_ORDER if tool in granted]
    return ordered + [f"mcp__{server}" for server in mcp_servers_of(caps)]


def missing_skills(spec: AgentSpec, skills_dir: Path) -> list[str]:
    """Profiles named by the contract that are missing from `skills_dir`."""
    return [skill for skill in spec.skills if not (skills_dir / skill / SKILL_MD).is_file()]


def check_skills(spec: AgentSpec, skills_dir: Path | None) -> None:
    """A named profile must exist on disk: the runtime silently skips a missing one."""
    if skills_dir is None:
        return
    missing = missing_skills(spec, skills_dir)
    if missing:
        raise FileNotFoundError(
            f"agent {spec.name} names profiles missing from {skills_dir}: {missing}"
        )


def load_agent(agent_dir: Path) -> tuple[AgentSpec, str]:
    """Read an agent package from the library: the contract plus the system prompt."""
    spec_path = agent_dir / AGENT_YAML
    prompt_path = agent_dir / PROMPT_MD
    if not spec_path.is_file():
        raise FileNotFoundError(f"no agent contract: {spec_path}")
    if not prompt_path.is_file():
        raise FileNotFoundError(f"no system prompt: {prompt_path}")

    spec = AgentSpec.model_validate(yaml.safe_load(spec_path.read_text(encoding="utf-8")))
    return spec, prompt_path.read_text(encoding="utf-8")


def render_agent(spec: AgentSpec, prompt: str) -> str:
    """Build the text of `.claude/agents/<slug>.md`."""
    slug = slug_of(spec.name)
    head: dict[str, object] = {
        "name": slug,
        # In the library the description is a folded multi-line scalar; in the frontmatter it
        # must be one line, otherwise the YAML reads differently from what was intended.
        "description": " ".join(spec.description.split()),
        "tools": ", ".join(tools_of(spec.needs)),
    }
    servers = mcp_servers_of(spec.needs)
    if servers:
        head["mcpServers"] = servers
    # Every agent: its role is its prompt, the document is its profile, the ports are its task.
    # The project's CLAUDE.md is for the developer session and costs the agent only tokens.
    head["omitClaudeMd"] = True
    if spec.skills:
        # A list, not a string: that is how the runtime describes the field, and that is how
        # YAML reads it without guessing the separator.
        head["skills"] = list(spec.skills)

    frontmatter = yaml.safe_dump(
        head,
        sort_keys=False,
        allow_unicode=True,
        width=10**6,
        default_flow_style=False,
    )
    marker = GENERATED_MARKER.format(name=spec.name)
    inputs = render_inputs(spec)
    tail = f"\n\n{inputs}" if inputs else ""
    return f"---\n{frontmatter}---\n\n{marker}\n\n{prompt.strip()}{tail}\n"


def render_inputs(spec: AgentSpec) -> str:
    """The agent's inputs from its contract, appended to its prompt.

    The contract in ``agent.yaml`` is what ``facet.wiring`` holds the scripts to; this puts the
    same text in front of the agent, so what a script hands and what the agent is told it gets
    come from one place.
    """
    if not spec.consumes:
        return ""
    lines = [
        "## Your inputs",
        "",
        "The task's INPUT block lists each input as `name: path`. What each name is:",
        "",
    ]
    names = {p.port for p in spec.consumes}
    for p in spec.consumes:
        need = "optional, may be absent" if p.optional else "required"
        how = ""
        if p.type.startswith("collection<"):
            one = p.port.removesuffix("s")
            # A form that is another input's own name belongs to that input, as in facet.wiring:
            # `sources` and `source` side by side are summaries and the files they summarise.
            stems = [p.port] + ([one] if one == p.port or one not in names else [])
            forms = list(
                dict.fromkeys(
                    [f"`{s}:<name>`" for s in stems] + [f"`{s}_<n>`" for s in stems[1:] or stems]
                )
            )
            how = (
                "; arrives as one line per item, named "
                + " or ".join(forms)
                + f", or as one line `{p.port}: <folder>` holding them all"
            )
        lines.append(f"- `{p.port}` ({need}{how}): {p.about}")
    return "\n".join(lines)


def emit_agent(agent_dir: Path, out_dir: Path, skills_dir: Path | None = None) -> Path:
    """Generate one definition file. Returns the path written.

    `skills_dir` is the profiles directory (`.claude/skills`); when given, the profiles named
    by the contract are checked on disk before the file is written.
    """
    spec, prompt = load_agent(agent_dir)
    check_skills(spec, skills_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    target = out_dir / f"{slug_of(spec.name)}.md"
    target.write_text(render_agent(spec, prompt), encoding="utf-8")
    return target


def emit_all(agents_dir: Path, out_dir: Path, skills_dir: Path | None = None) -> list[Path]:
    """Generate the definitions of every library agent, in a stable order."""
    packages = sorted(p for p in agents_dir.iterdir() if (p / AGENT_YAML).is_file())
    return [emit_agent(package, out_dir, skills_dir) for package in packages]
